.PHONY: help deps dev build test lint format

install: 
	npm install

dev: 
	npm run dev

build: 
	npm run build

lint: 
	npm run lint

vitest: 
	npx vitest src

format: 
	npm run format

deploy: 
	build
	npm run deploy
